import { test, expect } from '@playwright/test'
import { createHash } from 'node:crypto'
import { defaultEvents } from '../src/data/defaultEvents.js'
const password = 'Teste-local-123'
const roles = ['admin','organizador','financeiro','checkin','cliente']
test('Admin preserves Maps, reopens attractions collapsed and confirms visual save', async ({page}) => {
  await seed(page)
  await login(page,'admin')
  await page.getByRole('button',{name:'Eventos',exact:true}).click()
  await page.getByRole('button',{name:'Editar',exact:true}).first().click()
  await expect(page.locator('.attraction-collapse-toggle[aria-expanded="true"]')).toHaveCount(0)
  await page.getByLabel('Link do Google Maps (opcional)').fill('https://maps.app.goo.gl/ExampleLocation')
  await page.getByRole('button',{name:'Salvar',exact:true}).click()
  await page.getByRole('button',{name:'Editar',exact:true}).first().click()
  await expect(page.getByLabel('Link do Google Maps (opcional)')).toHaveValue('https://maps.app.goo.gl/ExampleLocation')
  await expect(page.locator('.attraction-collapse-toggle[aria-expanded="true"]')).toHaveCount(0)
  await page.getByRole('link',{name:'Experiência visual 3D'}).click()
  await page.locator('.ix-event-picker>div>a').first().click()
  await page.getByRole('button',{name:'Salvar experiência',exact:true}).click()
  await expect(page.locator('.ix-editor-notice.success')).toContainText('Experiência salva com sucesso')
})
async function seed(page) {
  await page.goto('/')
  await page.evaluate(({roles,hash,events})=>{
    localStorage.setItem('ingressos_auth_users_v1',JSON.stringify(roles.map(role=>({id:role,name:'Teste '+role,email:role==='admin'?'ingressosaltatemporada@gmail.com':role+'@example.test',passwordHash:hash,role,organizerId:'org-main',organizerName:'Organização principal',active:true}))))
    localStorage.setItem('ingressos_events_v1',JSON.stringify(events.map((e,i)=>({...e,organizerId:i===1?'org-other':'org-main',published:i!==2,ticketTypes:e.ticketTypes.map(t=>({...t,available:10}))}))))
    localStorage.setItem('ingressos_orders_v1',JSON.stringify([{id:'legacy',eventId:'2',eventTitle:'Sunset Experience',ticketId:'pista',quantity:1,total:99,fee:9,subtotal:90,buyer:{name:'Outro Cliente',email:'outro@example.test'},ticketCodes:[{code:'LEGACY-SECRET',used:false}]}]))
  },{roles,hash:createHash('sha256').update(password).digest('hex'),events:defaultEvents})
}
async function login(page,role,destination='/admin') {
  await page.goto(destination)
  await page.getByLabel('E-mail',{exact:true}).fill(role==='admin'?'ingressosaltatemporada@gmail.com':role+'@example.test')
  await page.getByLabel('Senha',{exact:true}).fill(password)
  await page.getByRole('button',{name:'Entrar',exact:true}).click()
}
async function buy(page,decline=false) {
  await page.getByLabel('Nome completo').fill('Cliente Teste')
  await page.getByLabel('CPF',{exact:true}).fill('52998224725')
  await page.getByLabel('Telefone com DDD').fill('41999999999')
  await page.getByLabel('Data de nascimento').fill('2000-01-01')
  if(decline){await page.getByLabel('Resultado da simulação').selectOption('declined');await page.getByRole('button',{name:'Confirmar compra simulada'}).click();await expect(page.getByRole('alert')).toContainText('recusado');await page.getByLabel('Resultado da simulação').selectOption('approved')}
  await page.getByRole('button',{name:'Confirmar compra simulada'}).click()
  await expect(page).toHaveURL(/\/ingressos$/)
}
test('catalog, checkout, QR, stock, cancellation and second-entry rejection',async({page})=>{
  const errors=[];page.on('pageerror',e=>errors.push(e.message))
  await seed(page)
  await page.goto('/eventos');await expect(page.locator('.event-card')).toHaveCount(2)
  await page.goto('/evento/green-night?preview=1');await expect(page.getByText('Evento não encontrado.')).toBeVisible()
  await login(page,'cliente','/checkout?event=1&ticket=pista&q=1&ref=instagram')
  await buy(page,true)
  await expect(page.locator('.my-ticket')).toHaveCount(1)
  await expect(page.locator('.my-ticket svg')).toHaveCount(1)
  let orders=await page.evaluate(()=>JSON.parse(localStorage.getItem('ingressos_platform_v2')).orders)
  expect(orders[0].source).toBe('instagram');expect(orders[0].total).toBe(164.89)
  const first=orders[0].ticketCodes[0].code
  await page.goto('/checkout?event=1&ticket=pista&q=1');await buy(page)
  orders=await page.evaluate(()=>JSON.parse(localStorage.getItem('ingressos_platform_v2')).orders)
  const second=orders[0].ticketCodes[0].code
  await page.getByRole('button',{name:'Sair',exact:true}).click()
  await login(page,'admin')
  await page.getByRole('button',{name:'Pedidos',exact:true}).click()
  page.on('dialog',dialog=>dialog.accept())
  await page.locator('.order-row').filter({hasText:orders[0].id}).getByRole('button',{name:'Cancelar pedido'}).click()
  await expect(page.locator('.order-row').filter({hasText:orders[0].id})).toContainText('Cancelado')
  await page.getByRole('button',{name:'Check-in',exact:true}).click()
  async function scan(code,text){await page.getByPlaceholder('ING-...').fill(code);await page.getByRole('button',{name:'Validar',exact:true}).click();await expect(page.locator('.scan-result')).toContainText(text)}
  await scan(second,'CANCELADO');await scan(first,'INGRESSO VÁLIDO');await scan(first,'JÁ UTILIZADO');await scan('INVALIDO','INVÁLIDO')
  expect(errors).toEqual([])
})
test('organizer, finance and check-in stay within their organization; customer route is denied',async({page})=>{
  await seed(page)
  for(const role of ['organizador','financeiro','checkin']) {
    await login(page,role)
    await expect(page.getByRole('button',{name:'Equipe',exact:true})).toHaveCount(0)
    if(role!=='checkin') {await page.getByRole('button',{name:'Pedidos',exact:true}).click();await expect(page.getByText('Outro Cliente',{exact:false})).toHaveCount(0)}
    if(role==='financeiro') await expect(page.getByRole('button',{name:'Eventos',exact:true})).toHaveCount(0)
    await page.getByRole('button',{name:'Sair',exact:true}).click()
  }
  await login(page,'cliente');await expect(page).toHaveURL(/\/ingressos$/);await expect(page.getByText('LEGACY-SECRET')).toHaveCount(0)
})
test('admin creates coupon and event, duplicates and archives without removing legacy data',async({page})=>{
  await seed(page);await login(page,'admin')
  await page.getByRole('button',{name:'Cupons',exact:true}).click()
  await page.getByLabel('Código',{exact:true}).fill('PROMO10')
  await page.getByRole('button',{name:'Salvar cupom'}).click();await expect(page.getByText('Cupom salvo.')).toBeVisible()
  await page.getByRole('button',{name:'Eventos',exact:true}).click()
  await page.getByRole('button',{name:'Novo evento',exact:true}).click()
  await page.getByLabel('Nome',{exact:true}).fill('Evento Teste Novo')
  await page.getByLabel('Publicado no site').check()
  await page.getByRole('button',{name:'Salvar',exact:true}).click()
  await expect(page.locator('.admin-event-copy').filter({hasText:'Evento Teste Novo'})).toHaveCount(1)
  const card=page.locator('.admin-event-list article').filter({hasText:'Evento Teste Novo'}).first()
  await card.getByRole('button',{name:'Duplicar',exact:true}).click()
  await page.getByRole('button',{name:'Cancelar',exact:true}).click()
  await expect(page.locator('.admin-event-list article').filter({hasText:'Evento Teste Novo'})).toHaveCount(2)
  await page.locator('.admin-event-list article').filter({hasText:'Evento Teste Novo - Cópia'}).getByRole('button',{name:'Arquivar',exact:true}).click()
  await expect(page.locator('.admin-event-list article').filter({hasText:'Evento Teste Novo - Cópia'})).toContainText('Arquivado')
  const count=await page.evaluate(()=>JSON.parse(localStorage.getItem('ingressos_events_v1')).length)
  expect(count).toBe(3)
})
test('mobile checkout and check-in layouts fit viewport',async({page})=>{
  await page.setViewportSize({width:390,height:844});await seed(page)
  await login(page,'cliente','/checkout?event=1&ticket=pista&q=1')
  expect(await page.evaluate(()=>document.documentElement.scrollWidth<=window.innerWidth+1)).toBe(true)
  await page.screenshot({path:'test-results/mobile-checkout.png',fullPage:true})
  await buy(page);await page.getByRole('button',{name:'Sair',exact:true}).click();await login(page,'checkin')
  expect(await page.evaluate(()=>document.documentElement.scrollWidth<=window.innerWidth+1)).toBe(true)
  await page.screenshot({path:'test-results/mobile-checkin.png',fullPage:true})
})
test('first admin setup and customer signup preserve existing events',async({page})=>{
 await page.goto('/admin')
 await page.getByLabel('Seu nome').fill('Admin Inicial')
 await expect(page.getByLabel('E-mail',{exact:true})).toHaveValue('ingressosaltatemporada@gmail.com')
 await expect(page.getByLabel('E-mail',{exact:true})).toHaveAttribute('readonly', '')
 await page.getByLabel('Senha',{exact:true}).fill(password)
 await page.getByRole('button',{name:'Criar administrador',exact:true}).click()
 await expect(page.getByRole('heading',{name:'Visão geral.'})).toBeVisible()
 await page.getByRole('button',{name:'Sair',exact:true}).click()
 await page.goto('/ingressos')
 await page.getByRole('button',{name:'Criar conta de cliente'}).click()
 await page.getByLabel('Seu nome').fill('Cliente Novo')
 await page.getByLabel('E-mail',{exact:true}).fill('novo@example.test')
 await page.getByLabel('Senha',{exact:true}).fill(password)
 await page.getByRole('button',{name:'Criar conta',exact:true}).click()
 await expect(page.getByRole('heading',{name:'Meus ingressos.'})).toBeVisible()
 await page.goto('/admin');await expect(page).toHaveURL(/\/ingressos$/)
 await page.goto('/eventos');await expect(page.locator('.event-card')).toHaveCount(3)
})
test('two simultaneous check-in tabs admit a ticket exactly once',async({page,context})=>{
 await seed(page);await login(page,'cliente','/checkout?event=1&ticket=pista&q=1');await buy(page)
 const code=await page.locator('.my-ticket code').innerText()
 await page.getByRole('button',{name:'Sair',exact:true}).click();await login(page,'checkin')
 const other=await context.newPage();await other.goto('/admin')
 await page.getByPlaceholder('ING-...').fill(code);await other.getByPlaceholder('ING-...').fill(code)
 await Promise.all([page.getByRole('button',{name:'Validar',exact:true}).click(),other.getByRole('button',{name:'Validar',exact:true}).click()])
 await expect(page.locator('.scan-result')).toBeVisible();await expect(other.locator('.scan-result')).toBeVisible()
 expect([await page.locator('.scan-result').innerText(),await other.locator('.scan-result').innerText()].sort()).toEqual(['INGRESSO VÁLIDO','JÁ UTILIZADO'].sort())
})
test('admin can create, change profile, reset password and deactivate a team member',async({page})=>{
 await seed(page);await login(page,'admin');await page.getByRole('button',{name:'Equipe',exact:true}).click()
 await page.getByLabel('Nome',{exact:true}).fill('Equipe Teste')
 await page.getByLabel('E-mail',{exact:true}).fill('equipe@example.test')
 await page.getByLabel('Senha inicial').fill(password)
 await page.getByRole('combobox',{name:'Perfil',exact:true}).selectOption('checkin')
 await page.getByRole('button',{name:'Criar acesso',exact:true}).click()
 const member=page.locator('.team-list article').filter({hasText:'equipe@example.test'})
 await expect(member).toBeVisible()
 await member.getByLabel('Perfil de Equipe Teste').selectOption('financeiro')
 await expect(member.getByLabel('Perfil de Equipe Teste')).toHaveValue('financeiro')
 page.on('dialog',dialog=>dialog.accept('Outra-senha-123'))
 await member.getByRole('button',{name:'Nova senha'}).click()
 await expect(page.getByText('Senha de Equipe Teste alterada.')).toBeVisible()
 await member.getByRole('button',{name:'Desativar',exact:true}).click()
 await expect(member.getByRole('button',{name:'Ativar',exact:true})).toBeVisible()
 await page.getByRole('button',{name:'Sair',exact:true}).click()
 await page.getByLabel('E-mail',{exact:true}).fill('equipe@example.test');await page.getByLabel('Senha',{exact:true}).fill('Outra-senha-123')
 await page.getByRole('button',{name:'Entrar',exact:true}).click()
 await expect(page.locator('.auth-error')).toContainText('desativado')
})

test('existing primary account is promoted without duplicates or data loss',async({page})=>{
 await seed(page)
 const before = await page.evaluate(()=>{
   const users=JSON.parse(localStorage.getItem('ingressos_auth_users_v1'))
   users[0]={...users[0],email:' MEDQUEST41@GMAIL.COM ',role:'cliente',active:false}
   localStorage.setItem('ingressos_auth_users_v1',JSON.stringify(users))
   return {users,events:localStorage.getItem('ingressos_events_v1'),orders:localStorage.getItem('ingressos_orders_v1')}
 })
 await login(page,'admin')
 await expect(page.getByRole('heading',{name:'Visão geral.'})).toBeVisible()
 for(const name of ['Eventos','Pedidos','Equipe','Financeiro','Check-in']) await expect(page.getByRole('button',{name,exact:true})).toBeVisible()
 await page.reload()
 const after=await page.evaluate(()=>({users:JSON.parse(localStorage.getItem('ingressos_auth_users_v1')),events:localStorage.getItem('ingressos_events_v1'),orders:localStorage.getItem('ingressos_orders_v1')}))
 expect(after.users).toEqual(before.users.map((u,i)=>i===0?{...u,email:'ingressosaltatemporada@gmail.com',role:'admin',active:true}:u))
 expect(after.events).toBe(before.events)
 expect(after.orders).toBe(before.orders)
 expect(after.users.every(u=>!('password' in u))).toBe(true)
})
test('bootstrap keeps an existing administrator and stores only the new password hash',async({page})=>{
 await seed(page)
 const oldUsers=await page.evaluate(()=>{
   const users=JSON.parse(localStorage.getItem('ingressos_auth_users_v1'))
   users[0].email='legacy-admin@example.test'
   localStorage.setItem('ingressos_auth_users_v1',JSON.stringify(users))
   return users
 })
 await page.goto('/admin')
 await page.getByLabel('Seu nome').fill('Administrador principal')
 await page.getByLabel('Senha',{exact:true}).fill(password)
 await page.getByRole('button',{name:'Criar administrador',exact:true}).click()
 await expect(page.getByRole('heading',{name:'Visão geral.'})).toBeVisible()
 const users=await page.evaluate(()=>JSON.parse(localStorage.getItem('ingressos_auth_users_v1')))
 expect(users.slice(1)).toEqual(oldUsers)
 expect(users[0]).toMatchObject({email:'ingressosaltatemporada@gmail.com',role:'admin',passwordHash:createHash('sha256').update(password).digest('hex')})
 expect(users[0]).not.toHaveProperty('password')
 await page.getByRole('button',{name:'Sair',exact:true}).click()
 await page.getByLabel('E-mail',{exact:true}).fill('legacy-admin@example.test')
 await page.getByLabel('Senha',{exact:true}).fill(password)
 await page.getByRole('button',{name:'Entrar',exact:true}).click()
 await page.getByRole('button',{name:'Equipe',exact:true}).click()
 const primary=page.locator('.team-list article').filter({hasText:'ingressosaltatemporada@gmail.com'})
 await primary.getByLabel('Perfil de Administrador principal').selectOption('cliente')
 await expect(page.getByText('O administrador principal deve manter acesso total.')).toBeVisible()
 await primary.getByRole('button',{name:'Desativar',exact:true}).click()
 const stored=await page.evaluate(()=>JSON.parse(localStorage.getItem('ingressos_auth_users_v1')))
 expect(stored[0]).toEqual(users[0])
})



