import {test,expect} from '@playwright/test'
import {defaultEvents} from '../src/data/defaultEvents.js'
import {createHash} from 'node:crypto'
test('guest multi-ticket checkout, confirmation, independent QR, PDF, reload and privacy on mobile',async({page})=>{
 await page.setViewportSize({width:390,height:844});await page.goto('/');await page.getByRole('button',{name:'Somente essenciais',exact:true}).click()
 const event={...defaultEvents[0],published:true,archived:false,ageRating:'18+',allowSameCpf:true}
 await page.evaluate(e=>localStorage.setItem('ingressos_events_v1',JSON.stringify([e])),event)
 await page.goto('/checkout?event='+event.id+'&ticket='+event.ticketTypes[0].id+'&q=2');await page.getByRole('button',{name:'Compra rápida sem conta'}).click()
 await page.getByLabel('Nome completo',{exact:true}).fill('Cliente Teste');await page.getByLabel('CPF',{exact:true}).fill('52998224725');await page.getByLabel('E-mail para receber os ingressos').fill('teste@example.test');await page.getByLabel('Telefone com DDD').fill('41999999999');await page.getByLabel('Data de nascimento',{exact:true}).fill('2000-01-01')
 const finish=page.getByRole('button',{name:'Confirmar compra simulada'});await expect(finish).toBeDisabled();await page.getByRole('button',{name:'Salvar / Confirmar participantes'}).click();await expect(page.getByRole('alert')).toContainText('18 anos')
 await page.getByLabel('Confirmo que eu e todos os portadores').check();await page.getByRole('button',{name:'Salvar / Confirmar participantes'}).click();await expect(finish).toBeEnabled();await finish.click();await expect(page).toHaveURL(/\/ingressos/)
 await expect(page.locator('.my-ticket')).toHaveCount(2);await expect(page.locator('.qr-box svg')).toHaveCount(2);const codes=await page.locator('.my-ticket code').allTextContents();expect(new Set(codes).size).toBe(2);await expect(page.getByRole('button',{name:'PDF / Salvar',exact:true})).toHaveCount(2)
 await page.reload();await expect(page.locator('.my-ticket')).toHaveCount(2);expect(await page.evaluate(()=>document.documentElement.scrollWidth<=window.innerWidth)).toBe(true);await page.screenshot({path:'../tickets-mobile16.png',fullPage:true})
})
test('login preserves general Home, event context and explicit tickets intent',async({page})=>{
 await page.goto('/');await page.getByRole('button',{name:'Somente essenciais',exact:true}).click();await page.evaluate(({events,hash})=>{localStorage.setItem('ingressos_auth_users_v1',JSON.stringify([{id:'buyer',email:'buyer@example.test',name:'Cliente Teste',role:'cliente',active:true,passwordHash:hash}]));localStorage.setItem('ingressos_events_v1',JSON.stringify(events))},{events:defaultEvents,hash:createHash('sha256').update('Teste-123').digest('hex')})
 async function login(){await page.getByLabel('E-mail',{exact:true}).fill('buyer@example.test');await page.getByLabel('Senha',{exact:true}).fill('Teste-123');await page.getByRole('button',{name:'Entrar',exact:true}).click()}
 await page.goto('/login');await login();await expect(page).toHaveURL(/\/eventos$/);await page.evaluate(()=>localStorage.removeItem('ingressos_auth_session_v1'));await page.reload();const target=await page.locator('.event-card').first().getAttribute('href');await page.goto('/login?returnTo='+encodeURIComponent(target));await login();await expect(page).toHaveURL(new RegExp(target+'$'));await page.evaluate(()=>localStorage.removeItem('ingressos_auth_session_v1'));await page.goto('/ingressos');await login();await expect(page).toHaveURL(/\/ingressos$/)
})
test('individual cards require each CPF and cookie preferences persist',async({page})=>{
 await page.goto('/');await page.getByRole('button',{name:'Configurar',exact:true}).click();await page.getByRole('button',{name:'Salvar escolhas'}).click();await page.reload();await expect(page.locator('.cookies16')).toHaveCount(0)
 const event={...defaultEvents[0],published:true,allowSameCpf:false};await page.evaluate(e=>localStorage.setItem('ingressos_events_v1',JSON.stringify([e])),event);await page.goto('/checkout?event='+event.id+'&ticket='+event.ticketTypes[0].id+'&q=2');await page.getByRole('button',{name:'Compra rápida sem conta'}).click();await expect(page.locator('.postits16 article')).toHaveCount(2)
 await page.getByRole('button',{name:'Salvar / Confirmar participantes'}).click();await expect(page.getByRole('alert')).toContainText('participante por ingresso')
})
test('public VIP validates age and registration then authorized organizer can check in once',async({page})=>{
 await page.goto('/');await page.getByRole('button',{name:'Somente essenciais',exact:true}).click();const event={...defaultEvents[0],published:true,ageRating:'18+',vipLists:[{id:'vip-test',name:'Lista VIP Teste',audience:'todos',limit:1,price:0,active:true,visible:true}]};await page.evaluate(e=>localStorage.setItem('ingressos_events_v1',JSON.stringify([e])),event);await page.reload();const href=await page.locator('.event-card').first().getAttribute('href');await page.goto(href);await page.getByRole('button',{name:'Participar',exact:true}).click();const form=page.locator('.vip16 form');await form.getByLabel('Nome completo').fill('Cliente Teste');await form.getByLabel('CPF',{exact:true}).fill('52998224725');await form.getByLabel('Telefone',{exact:true}).fill('41999999999');await form.getByLabel('Data de nascimento').fill('2000-01-01');await form.getByLabel('Confirmo que tenho 18 anos').check();await form.getByRole('button',{name:'Confirmar participação'}).click();await expect(page.locator('.vip16')).toContainText('Inscrição confirmada')
 await page.evaluate(()=>{const user={id:'organizer16',email:'organizer@example.test',name:'Organizador Teste',role:'organizador',organizerId:'org-main',active:true};const rows=JSON.parse(localStorage.getItem('ingressos_auth_users_v1'));rows.push(user);localStorage.setItem('ingressos_auth_users_v1',JSON.stringify(rows));localStorage.setItem('ingressos_auth_session_v1',user.id)});await page.goto('/admin/evento/'+event.id+'/dashboard');await page.getByRole('button',{name:'Carregar / atualizar inscritos'}).click();await expect(page.locator('.vip16')).toContainText('Cliente Teste');await page.getByRole('button',{name:'Confirmar entrada',exact:true}).click();await expect(page.locator('.vip16')).toContainText('used');await expect(page.getByRole('button',{name:'Confirmar entrada',exact:true})).toHaveCount(0)
})
