import { useMemo, useState } from 'react'
import { Link, useNavigate, useParams } from 'react-router-dom'
import { ArrowLeft, ArrowRight, CalendarDays, Check, ChevronRight, Clock3, MapPin, Minus, Plus, Share2, ShieldCheck, Sparkles, Ticket, Users } from 'lucide-react'
import Brand from '../components/Brand'
import { useEventStore } from '../store/EventStore'

const brl = (v) => v.toLocaleString('pt-BR', { style:'currency', currency:'BRL' })

export default function Evento() {
  const { id } = useParams(); const navigate = useNavigate(); const { events } = useEventStore()
  const event = useMemo(() => events.find(e => e.id === id), [events, id])
  const [selectedTicket, setSelectedTicket] = useState(null); const [quantity, setQuantity] = useState(1)
  if (!event || !event.published) return <div className="event-not-found"><Ticket size={42}/><h1>Evento não encontrado.</h1><Link to="/">Voltar para a página inicial <ArrowRight size={18}/></Link></div>
  const subtotal = selectedTicket ? selectedTicket.price * quantity : 0; const fee = subtotal * .10; const total = subtotal + fee
  function choose(ticket){ setSelectedTicket(ticket); setQuantity(1) }
  function checkout(){ if(!selectedTicket) return; navigate(`/checkout?event=${event.id}&ticket=${selectedTicket.id}&q=${quantity}`) }
  return <div className="event-page">
    <header className="event-page-header"><Link to="/" className="event-back"><ArrowLeft size={18}/>Eventos</Link><Brand/><button className="event-share" onClick={() => navigator.clipboard?.writeText(location.href)}><Share2 size={17}/>Compartilhar</button></header>
    <section className="event-hero"><div className="event-hero-image"><img src={event.image} alt={event.title}/></div><div className="event-hero-overlay"/><div className="event-hero-glow"/><div className="event-hero-content"><div className="event-status"><i/>{event.salesStatus}</div><span className="event-hero-category">{event.category}</span><h1>{event.title}</h1><div className="event-hero-info"><span><CalendarDays/><strong>{event.date}</strong></span><span><Clock3/><strong>{event.time}</strong></span><span><MapPin/><strong>{event.location}</strong></span></div><a href="#ingressos" className="primary-cta">Comprar ingresso <ArrowRight size={19}/></a></div></section>
    <main className="event-main">
      <section className="event-information"><div className="event-about"><span className="section-kicker"><Sparkles size={14}/>SOBRE O EVENTO</span><h2>Uma experiência criada para ser lembrada.</h2><p>{event.description}</p><div className="event-highlights">{event.highlights.map(h=><div key={h}><Check size={16}/>{h}</div>)}</div></div><aside className="event-location-card"><span className="location-icon"><MapPin/></span><small>LOCAL DO EVENTO</small><h3>{event.location}</h3><p>{event.address}</p><p>{event.city}</p><button>Ver localização <ChevronRight size={18}/></button></aside></section>
      <section className="attractions-section"><span className="section-kicker">ATRAÇÕES</span><h2>Prepare-se para a noite.</h2><div className="attraction-grid">{event.attractions.map((a,i)=><div className="attraction-card" key={a}><span>{String(i+1).padStart(2,'0')}</span><strong>{a}</strong><small>CONFIRMADO</small></div>)}</div></section>
      <section className="ticket-section" id="ingressos"><div className="ticket-section-title"><div><span className="section-kicker">ESCOLHA SUA EXPERIÊNCIA</span><h2>Ingressos disponíveis.</h2></div><div className="ticket-security"><ShieldCheck size={19}/><span>Compra segura<small>Ingresso digital protegido</small></span></div></div>
      <div className="purchase-layout"><div className="ticket-options">{event.ticketTypes.map(ticket => { const selected = selectedTicket?.id===ticket.id; return <button key={ticket.id} className={`ticket-option ${selected?'selected':''}`} onClick={()=>choose(ticket)}><div className="ticket-option-main"><div className="ticket-option-icon">{ticket.type==='table'?<Users/>:<Ticket/>}</div><div><span>{ticket.batch}</span><h3>{ticket.name}</h3><p>{ticket.description}</p></div></div><div className="ticket-option-price"><small>A partir de</small><strong>{brl(ticket.price)}</strong><span>{ticket.available} disponíveis</span></div><div className="ticket-selected-check"><Check size={17}/></div></button>})}</div>
      <aside className={`purchase-summary ${selectedTicket?'active':''}`}>{!selectedTicket ? <div className="empty-summary"><div><Ticket/></div><h3>Escolha seu ingresso</h3><p>Selecione uma opção ao lado para visualizar o resumo da sua compra.</p></div> : <><div className="summary-header"><span>SEU PEDIDO</span><small>Reserva ainda não confirmada</small></div><div className="summary-event"><img src={event.image} alt={event.title}/><div><strong>{event.title}</strong><span>{event.date} • {event.time}</span></div></div><div className="summary-ticket"><div><small>INGRESSO</small><strong>{selectedTicket.name}</strong><span>{selectedTicket.batch}</span></div><strong>{brl(selectedTicket.price)}</strong></div>{selectedTicket.type!=='table'&&<div className="quantity-row"><span>Quantidade</span><div className="quantity-control"><button onClick={()=>setQuantity(q=>Math.max(1,q-1))}><Minus size={16}/></button><strong>{quantity}</strong><button onClick={()=>setQuantity(q=>Math.min(10, selectedTicket.available, q+1))}><Plus size={16}/></button></div></div>}<div className="summary-values"><div><span>Subtotal</span><strong>{brl(subtotal)}</strong></div><div><span>Taxa de serviço</span><strong>{brl(fee)}</strong></div></div><div className="summary-total"><span>Total</span><strong>{brl(total)}</strong></div><button className="checkout-button" onClick={checkout}>Continuar para checkout <ArrowRight size={19}/></button><div className="summary-security"><ShieldCheck size={16}/>Ambiente seguro e ingresso protegido.</div></>}</aside></div></section>
    </main><footer className="event-footer-page"><Brand/><span>© 2026 • Todos os direitos reservados</span></footer>
  </div>
}
