import LegalDocument from './LegalDocument'
import { draftDocuments } from '../services/legal'
import {Link,useParams} from 'react-router-dom'
import {institutionalLinks} from '../components/PublicChrome'
const content={
 'quem-somos':['Somos a Ingressos Experiences, uma empresa de venda de ingressos de Pato Branco-PR. Conectamos pessoas a eventos e organizadores por meio de ingressos digitais.','CNPJ: 65.586.495/0001-28.'],
 privacidade:['Tratamos dados de identificação e contato para processar pedidos, identificar portadores e permitir validação na entrada. Nome, CPF, nascimento, celular e e-mail são solicitados conforme o fluxo.','Pagamentos são processados pelo Mercado Pago; a plataforma não armazena dados completos de cartão. O Supabase protege autenticação e pedidos com permissões por conta e evento.','A localização é solicitada apenas ao clicar em Usar minha localização e não é gravada por padrão. Métricas opcionais dependem de sua escolha no banner.','Para solicitar acesso, correção ou exclusão de dados, use o atendimento oficial informado nesta plataforma. Registros de pedidos podem precisar ser conservados conforme obrigações aplicáveis. O prazo de retenção e os responsáveis devem ser definidos pela operação antes da publicação.'],
 termos:['Confira data, local, classificação etária, lote e regras do evento antes de confirmar. O organizador é responsável pela realização e pelas informações do evento.','Pedidos pagos liberam ingressos após confirmação do provedor. Uma reserva pendente não garante entrada. Cancelamentos, reembolsos e alterações devem ser solicitados pelo atendimento, respeitando as regras aplicáveis e os direitos do consumidor.','Não compartilhe códigos de entrada com desconhecidos. Cada QR Code é independente e aceita uma validação.'],
 cookies:['Usamos armazenamento essencial para autenticação, preferências de idioma e região, e sua escolha de privacidade.','Métricas opcionais registram interesse no evento, abertura de checkout e compartilhamento, sem apresentar compras fictícias. Você pode revisar sua escolha no rodapé.'],
 duvidas:['Onde encontro meus ingressos? Acesse Meus ingressos após comprar. Na compra rápida, preserve a sessão deste navegador.','Posso usar o mesmo CPF? Quando o evento permitir, cada unidade recebe um QR independente.','Não recebi o e-mail? Confira o status do pedido. O envio depende de um serviço transacional configurado; a tela informa quando estiver indisponível.','Como salvo em PDF? Abra um ingresso confirmado, toque em PDF e escolha Salvar como PDF na impressão.'],
 contato:['O atendimento oficial será exibido quando o e-mail ou WhatsApp da plataforma estiver configurado.','Para dúvidas específicas, use o WhatsApp do evento quando disponível. Nunca envie senhas ou dados completos de cartão.'],
 recomendacoes:['Apresente um documento quando solicitado. Respeite a classificação etária e as regras do evento.','Confira o nome do portador. Cada ingresso é de uso único. Não compre códigos em canais não oficiais.','Evite divulgar seu QR em redes sociais. Baixe o ingresso antes de sair e mantenha o celular carregado.'],
 pagamentos:['Eventos podem oferecer ingressos gratuitos, Pix ou cartão, conforme sua configuração.','O total e as taxas aparecem antes do pagamento. A reserva tem prazo; pagamentos em análise não liberam QR.','O ingresso gratuito é confirmado pelo servidor sem cobrança. Pagamentos reais dependem da configuração segura do Mercado Pago.']}
export default function Institutional(){const {slug}=useParams();if(draftDocuments[slug])return <LegalDocument key={slug} slug={slug}/>;const title=institutionalLinks.find(([key])=>key===slug)?.[1];return <main className="institutional16"><Link to="/eventos">← Eventos</Link><h1>{title||'Página não encontrada'}</h1>{(content[slug]||[]).map(p=><p key={p}>{p}</p>)}<p>Ingressos Experiences • Pato Branco-PR • CNPJ 65.586.495/0001-28</p>{slug==='contato'&&<><p>{import.meta.env.VITE_PUBLIC_CONTACT_EMAIL||'E-mail oficial a configurar'}</p>{import.meta.env.VITE_PUBLIC_CONTACT_WHATSAPP&&<a href={'https://wa.me/'+import.meta.env.VITE_PUBLIC_CONTACT_WHATSAPP.replace(/\D/g,'')}>Falar no WhatsApp</a>}</>}</main>}
