import { useEffect, useState } from 'react'
import { Link } from 'react-router-dom'
import { draftDocuments, defaultCompany, legalCatalog } from '../services/legal'
import './LegalDocument.css'
export default function LegalDocument({slug}) {
 const fallback=draftDocuments[slug]
 const [record,setRecord]=useState(null),[company,setCompany]=useState(defaultCompany)
 useEffect(()=>{let active=true;legalCatalog().then(c=>{if(active){setRecord(c.documents.find(d=>d.slug===slug&&d.published)||null);setCompany(c.company)}}).catch(()=>{});return()=>{active=false}},[slug])
 const content=record?JSON.parse(record.content):fallback.content
 const pending=!record
 return <main className="legal-page"><Link to="/eventos">← Voltar aos eventos</Link><header><span className="section-kicker">TRANSPARÊNCIA E DIREITOS</span><h1>{content.title}</h1><p>Versão {record?.version||content.version} • Atualização {content.updatedAt.split('-').reverse().join('/')}</p>{pending&&<p className="legal-pending" role="status">MINUTA PARA REVISÃO — pendente de identificação empresarial e revisão jurídica. Ainda não disponível para aceite contratual.</p>}</header><div className="legal-layout"><nav aria-label="Sumário do documento"><strong>Sumário</strong>{content.sections.map(s=><a key={s.id} href={'#'+s.id}>{s.title}</a>)}<Link to="/preferencias-legais">Meus aceites e preferências</Link></nav><article><section className="legal-identity"><h2>Identificação empresarial</h2><dl>{[['Nome fantasia',company.tradeName],['Razão social',company.legalName],['CNPJ informado',company.cnpj],['Endereço',company.address],['Cidade',company.city]].map(([title,value])=><div key={title}><dt>{title}</dt><dd>{value||'Pendente de confirmação'}</dd></div>)}</dl><p>Suporte: <a href={'mailto:'+company.supportEmail}>{company.supportEmail}</a><br/>Privacidade: <a href={'mailto:'+company.privacyEmail}>{company.privacyEmail}</a><br/>Jurídico: <a href={'mailto:'+company.legalEmail}>{company.legalEmail}</a></p></section>{content.sections.map(s=><section key={s.id} id={s.id}><h2>{s.title}</h2>{s.paragraphs.map(p=><p key={p}>{p}</p>)}</section>)}<section><h2>Referências oficiais</h2><ul>{content.references.map(r=><li key={r.url}><a href={r.url} target="_blank" rel="noopener noreferrer">{r.title}</a></li>)}</ul><p>{pending?'Minuta pendente de aprovação.':'Conteúdo aprovado pela responsável pela plataforma. Essa aprovação não equivale a revisão por advogado.'} Nenhum documento oferece proteção jurídica absoluta.</p><small>SHA-256 do conteúdo: {record?.content_hash||fallback.hash}</small></section></article></div></main>
}
