import { paged } from '../lib/pagination'
import { useEffect, useState } from 'react'
import { Link } from 'react-router-dom'
import { supabase,result } from '../lib/supabase'
import { useAuth,PRIMARY_ADMIN_EMAIL } from '../store/AuthStore'
import { defaultCompany } from '../services/legal'
import './LegalDocument.css'
export default function LegalPreferences(){
 const {currentUser}=useAuth();const owner=currentUser?.role==='admin'&&currentUser.email?.toLowerCase()===PRIMARY_ADMIN_EMAIL
 const [history,setHistory]=useState([]),[marketing,setMarketing]=useState(null),[company,setCompany]=useState(defaultCompany),[message,setMessage]=useState(''),[busy,setBusy]=useState(false)
 useEffect(()=>{let active=true;if(supabase&&currentUser){Promise.all([result(paged(()=>supabase.from('legal_acceptances').select('*',{count:'exact'}).order('accepted_at',{ascending:false}).order('id'))),result(supabase.from('marketing_preferences').select('*').eq('user_id',currentUser.id).order('recorded_at',{ascending:false}).limit(1)),result(supabase.from('legal_config').select('company').single())]).then(([rows,prefs,cfg])=>{if(active){setHistory(rows);setMarketing(prefs[0]?.enabled??false);setCompany(cfg.company)}}).catch(()=>{if(active)setMessage('Módulo jurídico ainda não instalado. As versões estão disponíveis como minutas.')})}return()=>{active=false}},[currentUser])
 async function changeMarketing(enabled){setBusy(true);try{await result(supabase.rpc('set_marketing_consent',{enabled}));setMarketing(enabled);setMessage(enabled?'Consentimento comercial registrado.':'Consentimento comercial revogado.')}catch{setMessage('Não foi possível registrar sua escolha. Tente novamente ou procure o atendimento.')}finally{setBusy(false)}}
 return <main className="legal-page"><Link to="/eventos">← Eventos</Link><h1>Meus aceites e privacidade</h1>{!currentUser?<p><Link to="/login?returnTo=%2Fpreferencias-legais">Entre na sua conta</Link> para consultar seus registros.</p>:<><section className="legal-controls"><h2>Comunicações comerciais</h2><p>{marketing===true?'Você optou por receber novidades.':'Você não autorizou o recebimento de novidades.'}</p><button className="ghost-btn" disabled={busy||!supabase} onClick={()=>changeMarketing(marketing!==true)}>{marketing===true?'Revogar consentimento':'Quero receber novidades'}</button></section>{owner&&<form className="legal-controls" onSubmit={async e=>{e.preventDefault();setBusy(true);try{await result(supabase.rpc('update_legal_company',{details:company}));setMessage('Identificação salva como pendente de revisão. Nenhum documento foi publicado.')}catch(err){setMessage(err.message)}finally{setBusy(false)}}}><h2>Identidade empresarial • Admin Geral</h2><div className="form-grid">{[['legalName','Razão social'],['tradeName','Nome fantasia'],['cnpj','CNPJ'],['address','Endereço completo'],['city','Cidade'],['supportEmail','E-mail de suporte'],['privacyEmail','E-mail de privacidade'],['legalEmail','Contato jurídico']].map(([key,label])=><label key={key}>{label}<input value={company[key]||''} onChange={e=>setCompany({...company,[key]:e.target.value})}/></label>)}</div><button className="ghost-btn" disabled={busy||!supabase}>Salvar para revisão</button></form>}<h2>{owner?'Histórico de aceites • consulta controlada':'Meu histórico de aceites'}</h2><p>Horários registrados no servidor em UTC. O histórico completo fica preservado e disponível conforme as permissões da conta.</p><div className="legal-history"><table><thead><tr>{owner&&<th>Conta</th>}<th>Documento</th><th>Versão</th><th>Data UTC</th><th>Origem</th></tr></thead><tbody>{history.map(row=><tr key={row.id}>{owner&&<td>{row.user_id}</td>}<td>{row.slug}</td><td>{row.version}<br/><small>{row.content_hash}</small></td><td>{row.accepted_at}</td><td>{row.origin}</td></tr>)}</tbody></table></div>{!history.length&&<p>Nenhum aceite registrado nesta consulta.</p>}</>}{message&&<p role="status">{message}</p>}<p>Canal de privacidade: <a href={'mailto:'+company.privacyEmail}>{company.privacyEmail}</a></p></main>
}
