import { useState } from 'react'
import { Link, useLocation } from 'react-router-dom'
import { QRCodeSVG } from 'qrcode.react'
import Brand from '../components/Brand'
import { useEventStore } from '../store/EventStore'
import { useAuth } from '../store/AuthStore'
import { ownsOrder, approved } from '../utils/commerce'
export default function MeusIngressos() {
  const { orders, isLocalDemo, cancelOrder, refresh } = useEventStore()
  const { currentUser, logout } = useAuth()
  const location = useLocation()
  const [now]=useState(()=>Date.now())
  const mine = orders.filter(order => ownsOrder(currentUser, order))
  return <div className="tickets-page"><header className="simple-header"><Link to="/eventos">Eventos</Link><Brand/><button className="ghost-btn" onClick={logout}>Sair</button></header><main className="tickets-wrap"><span className="section-kicker">MINHA CONTA • {currentUser.name}</span><h1>Meus ingressos.</h1>{location.state?.approved && <p role="status" className="team-success">{isLocalDemo ? 'Compra simulada aprovada. Seus ingressos estão abaixo.' : 'Pedido registrado. Confira o status abaixo.'}</p>}{isLocalDemo ? <p className="demo-warning">Demonstração local. Mantenha este navegador para acessar os ingressos.</p> : <><button className="ghost-btn" onClick={refresh}>Atualizar pedidos</button>{mine.map(order=><section className="admin-panel" key={order.id}><strong>{order.eventTitle}</strong><p>Pedido {order.id} • {{pending:'Pendente',approved:'Confirmado',cancelled:'Cancelado',refunded:'Estornado'}[order.status]}</p><details><summary>Histórico do pedido</summary>{(order.orderHistory||[]).map(h=><p key={h.id}>{new Date(h.created_at).toLocaleString('pt-BR')} • {{pending:'Pendente',approved:'Confirmado',cancelled:'Cancelado',refunded:'Estornado'}[h.to_status]}</p>)}</details><p>Total: {Number(order.total).toLocaleString('pt-BR',{style:'currency',currency:'BRL'})}</p>{order.status==='pending'&&<><p>{new Date(order.expiresAt).getTime()>now?'Reserva até '+new Date(order.expiresAt).toLocaleString('pt-BR'):'Reserva expirada. Faça um novo pedido.'} • Pagamento online não habilitado.</p><button className="ghost-btn" onClick={async()=>{try{await cancelOrder(order.id)}catch(err){window.alert(err.message)}}}>Cancelar reserva</button></>}</section>)}</>}<button className="ghost-btn" onClick={()=>window.print()}>Imprimir / salvar PDF</button>{mine.length===0?<div className="tickets-empty"><h2>Você ainda não possui ingressos.</h2><Link to="/eventos" className="primary-cta">Explorar eventos</Link></div>:<div className="my-ticket-grid">{mine.flatMap(order=>(order.ticketCodes || []).map((ticket,index)=>{const cancelled = !approved(order) || ticket.status === 'cancelled'; return <article className="my-ticket" key={ticket.code}><img src={order.eventImage} alt={order.eventTitle}/><div className="my-ticket-content"><span>{order.eventDate} • {order.eventTime}</span><h2>{order.eventTitle}</h2><p>{order.buyer?.name}</p><p>{order.ticketName} • {order.batch} • {index+1}/{order.quantity}</p><p>{order.unitLabel}</p>{!cancelled && !ticket.used && <div className="qr-box"><QRCodeSVG value={ticket.code} size={180}/></div>}<code>{ticket.code}</code><div className={'ticket-status ' + (cancelled || ticket.used ? 'used' : 'valid')}>{cancelled ? 'Cancelado' : ticket.used ? 'Já utilizado' : 'Válido'}</div><small>Pedido {order.id}</small></div></article>}))}</div>}</main></div>
}
