/* oxlint-disable react/only-export-components -- Optional activity recorder shares consent handling. */
import {useEffect,useState} from 'react'
import {supabase,result} from '../lib/supabase'
import {partyMessages} from '../utils/partyMessages'
import {countdown} from '../utils/experience'
const consent=()=>{try{return JSON.parse(localStorage.getItem('ingressos_cookies')||'{}').analytics===true}catch{return false}}
let visitor
export async function recordActivity(eventId,kind){if(!consent()||!supabase)return;visitor ||= crypto.randomUUID();try{await result(supabase.rpc('record_event_activity',{target:eventId,visitor,kind}))}catch{/* Optional metrics never block purchases. */}}
export default function Activity({event,full=false}){const [stats,setStats]=useState({looking:0,today:0}),[index,setIndex]=useState(0);useEffect(()=>{let active=true;const load=async()=>{if(supabase){try{const value=await result(supabase.rpc('event_activity_summary',{target:event.id}));if(active)setStats(value)}catch{}}};load();if(full&&event.activityMode!=='off')recordActivity(event.id,'view');const timer=setInterval(()=>{load();if(full&&event.activityMode!=='off')recordActivity(event.id,'view');setIndex(i=>(i+1)%partyMessages.length)},30000);return()=>{active=false;clearInterval(timer)}},[event.id,event.activityMode,full]);const simulation=event.activityMode==='initial';const looking=event.activityMode==='off'?0:simulation?Math.max(0,Math.min(200,(Number(event.activityMin)||0)+index%Math.max(1,(Number(event.activityMax)||0)-(Number(event.activityMin)||0)+1))):stats.looking;if(event.activityMode==='off')return null;return <div className={full?'activity16':'activity16 compact'}><span className="flame16">{full&&<small>Olhando agora<br/></small>}🔥 {looking} olhando{simulation?' • estimativa de interesse':''}</span><span>{full&&<small>Contagem<br/></small>}{countdown(event)}</span>{full&&<><span><small>Movimento hoje<br/></small>{simulation?'Interesse estimado':stats.today+' interações'}</span><p className="party-note16">{partyMessages[index]}</p></>}</div>}
