import { useState } from 'react'
import { useEventStore } from '../store/EventStore'
import { useAuth } from '../store/AuthStore'
import { approved, ownsEvent } from '../utils/commerce'
import { formatCpf, matchesBuyerSearch } from '../utils/buyerSearch'
import Payouts from './Payouts'
import { payoutAmount } from '../utils/fees'
const brl = v => Number(v || 0).toLocaleString('pt-BR', { style: 'currency', currency: 'BRL' })
function download(name, rows) {
  const cell = v => '"' + String(v ?? '').replace(/^\s*[=+@-]/, "'$&").replaceAll('"', '""') + '"'
  const url = URL.createObjectURL(new Blob(['\uFEFF' + rows.map(row=>row.map(cell).join(';')).join('\r\n')], {type:'text/csv;charset=utf-8'}))
  const a = document.createElement('a'); a.href = url; a.download = name; a.click(); setTimeout(()=>URL.revokeObjectURL(url),1000)
}
export default function AdminOperations({ tab, eventId = '' }) {
  const { events, orders, coupons, history, saveCoupon, recordPayout, isLocalDemo } = useEventStore()
  const { currentUser } = useAuth()
  const scoped = events.filter(e=>ownsEvent(currentUser,e) && (!eventId || String(e.id)===eventId))
  const sales = orders.filter(o=>scoped.some(e=>e.id===o.eventId))
  const paid = sales.filter(approved)
  const visibleCoupons = coupons.filter(c=>!eventId || String(c.eventId)===eventId)
  const visibleHistory = history.filter(h=>!eventId || String(h.eventId)===eventId)
  const [draft,setDraft] = useState({ eventId: scoped[0]?.id || '', code:'', type:'percent', value:10, limit:0, expiresAt:'', active:true })
  const [message,setMessage] = useState('')
  const [customerSearch,setCustomerSearch] = useState('')
  const canViewCpf = ['admin','organizador'].includes(currentUser.role)
  async function save(e) { e.preventDefault(); try { if(eventId && !scoped.length)throw new Error("Evento não disponível para este acesso."); await saveCoupon({...draft,eventId:eventId||draft.eventId}); setMessage('Cupom salvo.'); setDraft({...draft,code:''}) } catch(err) { setMessage(err.message) } }
  const customers = [...new Map(sales.filter(o=>o.buyer?.email).map(o=>[String(o.buyer.cpf||'').replace(/\D/g,'')||o.buyer.email,o.buyer])).values()].filter(buyer=>matchesBuyerSearch(buyer,customerSearch))
  return <><div className="admin-title"><h1>{{customers:'Clientes',coupons:'Cupons',finance:'Financeiro',reports:'Relatórios',history:'Histórico'}[tab]}.</h1></div>
    {tab==='finance' && <Payouts orders={sales} events={scoped} canRecord={currentUser.role==='admin'} recordPayout={recordPayout} isLocalDemo={isLocalDemo}/>}
    {tab==='customers' && canViewCpf && <section className="admin-panel"><div className="form-grid"><label>Buscar cliente por nome, e-mail ou CPF<input value={customerSearch} onChange={e=>setCustomerSearch(e.target.value)} placeholder="CPF com ou sem pontos e traço"/></label></div>{customers.length===0 && <p>Nenhum cliente encontrado para este evento ou busca.</p>}{customers.map(b=><div className="order-row" key={String(b.cpf||'').replace(/\D/g,'')||b.email}><div><strong>{b.name}</strong><span>CPF: {formatCpf(b.cpf)}</span><span>{b.email}</span></div><span>{b.phone}</span></div>)}</section>}
    {['finance','reports'].includes(tab) && <><div className="admin-stats">{[['Vendas aprovadas',brl(paid.reduce((s,o)=>s+o.total,0))],['Taxas',brl(paid.reduce((s,o)=>s+Number(o.platformFee??o.fee??0),0))],['Valor dos ingressos',brl(paid.reduce((s,o)=>s+o.subtotal-(o.discount||0),0))],['Cancelados',sales.filter(o=>['cancelled','refunded'].includes(o.status)).length]].map(([label,value])=><div key={label}><span>{label}</span><strong>{value}</strong></div>)}</div><section className="admin-panel"><p className="demo-warning">{isLocalDemo ? 'Valores de simulação. Não representam pagamentos reais.' : 'Pedidos registrados no banco. Valores confirmados não representam saldo de repasse.'}</p><button className="primary-small" onClick={()=>download('relatorio-vendas.csv',[['Pedido','Evento','Status','Cliente','Quantidade','Subtotal','Desconto','Comissão plataforma','Tarifa Mercado Pago','Saldo organizador','Repasse','Referência repasse','Total','Origem','Data'],...sales.map(o=>[o.id,o.eventTitle,o.status||'approved',o.buyer?.name,o.quantity,o.subtotal,o.discount||0,o.platformFee??o.fee??0,o.providerFee??'A apurar',payoutAmount(o)??'A apurar',o.payoutStatus==='paid'?'Realizado':'Pendente',o.payoutReference||'',o.total,o.source||'direto',o.createdAt])])}>Exportar vendas CSV</button><h2>Por evento e origem</h2>{scoped.map(e=><div className="order-row" key={e.id}><strong>{e.title}</strong><span>{brl(paid.filter(o=>o.eventId===e.id).reduce((s,o)=>s+o.total,0))}</span></div>)}{[...new Set(paid.map(o=>o.source||'direto'))].map(source=><div className="order-row" key={source}><span>{source}</span><strong>{paid.filter(o=>(o.source||'direto')===source).length} pedidos</strong></div>)}</section></>}
    {tab==='coupons' && <><form className="admin-panel buyer-form" onSubmit={save}><h2>Novo cupom</h2><div className="form-grid"><label>Evento<select required={isLocalDemo||currentUser.role!=='admin'} value={draft.eventId} disabled={Boolean(eventId)} onChange={e=>setDraft({...draft,eventId:e.target.value})}>{!eventId && <option value="">{!isLocalDemo&&currentUser.role==='admin'?'Global — todos os eventos':'Selecione'}</option>}{scoped.map(e=><option key={e.id} value={e.id}>{e.title}</option>)}</select></label><label>Código<input required value={draft.code} onChange={e=>setDraft({...draft,code:e.target.value.toUpperCase()})}/></label><label>Tipo<select value={draft.type} onChange={e=>setDraft({...draft,type:e.target.value})}><option value="percent">Percentual</option><option value="fixed">Valor em reais</option></select></label><label>{draft.type==='percent'?'Porcentagem de desconto (%)':'Desconto em reais (R$)'}<input required type="number" min="0.01" max={draft.type==='percent'?100:undefined} step="0.01" value={draft.value} onChange={e=>setDraft({...draft,value:e.target.value})}/></label><label>Limite de pedidos (0 = ilimitado)<input type="number" min="0" value={draft.limit} onChange={e=>setDraft({...draft,limit:e.target.value})}/></label><label>Limite por cliente (0 = ilimitado)<input type="number" min="0" value={draft.perUserLimit||0} onChange={e=>setDraft({...draft,perUserLimit:Number(e.target.value)})}/></label><label>Lote opcional<select value={draft.ticketId||''} onChange={e=>setDraft({...draft,ticketId:e.target.value})}><option value="">Todos</option>{scoped.find(e=>e.id===draft.eventId)?.ticketTypes.map(t=><option key={t.id} value={t.id}>{t.name} • {t.batch}</option>)}</select></label><label>Início da validade<input type="date" value={draft.startsAt?.slice(0,10)||''} onChange={e=>setDraft({...draft,startsAt:e.target.value})}/></label><label>Validade<input type="date" value={draft.expiresAt} onChange={e=>setDraft({...draft,expiresAt:e.target.value})}/></label></div><button className="primary-small">Salvar cupom</button><p role="status">{message}</p></form><section className="admin-panel">{visibleCoupons.map(c=><div className="order-row" key={c.id}><div><strong>{c.code} — {c.type==='percent'?c.value+'%':brl(c.value)}</strong><span>{c.eventId?scoped.find(e=>e.id===c.eventId)?.title:'Todos os eventos'}</span></div><button className="ghost-btn" onClick={async()=>{try {await saveCoupon({...c,active:!c.active})}catch(err){setMessage(err.message)}}}>{c.active?'Desativar':'Ativar'}</button><button className="ghost-btn" onClick={()=>setDraft(c)}>Editar cupom</button></div>)}</section></>}
    {tab==='history' && <section className="admin-panel">{visibleHistory.length===0&&<p>Nenhuma operação registrada ainda.</p>}{visibleHistory.map(h=><div className="order-row" key={h.id}><div><strong>{h.action}</strong><span>{h.actor} • {scoped.find(e=>e.id===h.eventId)?.title}</span></div><time>{new Date(h.at).toLocaleString('pt-BR')}</time></div>)}</section>}
  </>
}
