import { useState } from 'react'
import { useAuth } from '../store/AuthStore'
import { useEventStore } from '../store/EventStore'
import { rpc } from '../services/remoteData'
export default function OrganizationManager(){
 const {organizations,saveOrganization,users}=useAuth();const {events,summary=[],checkins=[]}=useEventStore()
 const [name,setName]=useState(''),[message,setMessage]=useState(''),[userId,setUserId]=useState(''),[eventId,setEventId]=useState('')
 async function run(fn){try{await fn();setMessage('Alteração salva.')}catch(err){setMessage(err.message)}}
 return <section className="admin-panel"><h2>Organizadores e autorizações</h2><form onSubmit={e=>{e.preventDefault();run(()=>saveOrganization({name,active:true}))}}><label>Nova organização<input required minLength={2} value={name} onChange={e=>setName(e.target.value)}/></label><button className="primary-small">Criar organização</button></form>{organizations.map(org=><div className="order-row" key={org.id}><strong>{org.name}</strong><button className="ghost-btn" onClick={()=>{const label=window.prompt('Nome da organização',org.name);if(label)run(()=>saveOrganization({...org,name:label}))}}>Editar</button><button className="ghost-btn" onClick={()=>run(()=>saveOrganization({...org,active:!org.active}))}>{org.active?'Desativar':'Ativar'}</button><button className="ghost-btn" onClick={()=>{const phone=window.prompt('WhatsApp do organizador (país + DDD + número)',org.whatsapp||'');if(phone!==null)run(()=>saveOrganization({...org,whatsapp:phone}))}}>WhatsApp</button></div>)}<h3>Autorizar check-in por evento</h3><label>Operador<select value={userId} onChange={e=>setUserId(e.target.value)}><option value="">Selecione</option>{users.filter(u=>u.role==='checkin').map(u=><option key={u.id} value={u.id}>{u.name}</option>)}</select></label><label>Evento autorizado<select value={eventId} onChange={e=>setEventId(e.target.value)}><option value="">Selecione</option>{events.map(e=><option key={e.id} value={e.id}>{e.title}</option>)}</select></label>{[true,false].map(enabled=><button className="ghost-btn" disabled={!userId||!eventId} key={String(enabled)} onClick={()=>run(()=>rpc('assign_checkin',{member_id:userId,event:eventId,enabled}))}>{enabled?'Autorizar':'Revogar'}</button>)}<p role="status">{message}</p><h3>Entradas registradas</h3>{summary.map(s=><p key={s.event_id}>{events.find(e=>e.id===s.event_id)?.title}: {s.checked_in} de {s.issued}</p>)}<small>{checkins.length} registros recentes disponíveis no check-in.</small></section>
}
