/* oxlint-disable react/only-export-components -- Public labels and shell components share this module. */
import {useEffect,useState} from 'react'
import {Link} from 'react-router-dom'
const texts={pt:{events:'Eventos',tickets:'Meus ingressos',account:'Criar conta',discover:'Descubra o evento que combina com você',near:'Eventos perto de você'},es:{events:'Eventos',tickets:'Mis entradas',account:'Crear cuenta',discover:'Descubre el evento que va contigo',near:'Eventos cerca de ti'},en:{events:'Events',tickets:'My tickets',account:'Create account',discover:'Discover the event that suits you',near:'Events near you'}}
export const publicText=key=>texts[localStorage.getItem('ingressos_language')||'pt']?.[key]||texts.pt[key]
export function Preferences(){const [language,setLanguage]=useState(()=>localStorage.getItem('ingressos_language')||'pt'),[country,setCountry]=useState(()=>localStorage.getItem('ingressos_country')||'BR');return <div className="preferences16"><label>Idioma<select value={language} onChange={e=>{setLanguage(e.target.value);localStorage.setItem('ingressos_language',e.target.value);window.dispatchEvent(new Event('ingressos-language'))}}><option value="pt">Português Brasil</option><option value="es">Español</option><option value="en">English</option></select></label><label>País / região<select value={country} onChange={e=>{setCountry(e.target.value);localStorage.setItem('ingressos_country',e.target.value)}}>{[['BR','Brasil'],['PY','Paraguai'],['AR','Argentina'],['US','EUA']].map(([id,name])=><option key={id} value={id}>{name}</option>)}</select></label></div>}
export const institutionalLinks=[['quem-somos','Quem somos'],['privacidade','Política de Privacidade'],['termos','Termos de Uso'],['cookies','Política de Cookies'],['duvidas','Dúvidas frequentes'],['contato','Contato / Atendimento'],['recomendacoes','Recomendações e regras gerais do ingresso'],['pagamentos','Formas de pagamento']]
export function Footer(){return <footer className="footer16"><h2>Ingressos Experiences</h2><p>Empresa de venda de ingressos • Pato Branco-PR • CNPJ 65.586.495/0001-28</p><nav>{institutionalLinks.map(([slug,label])=><Link key={slug} to={'/institucional/'+slug}>{label}</Link>)}<Link to="/login?cadastro=1">{publicText('account')}</Link><Link to="/criar-evento">Criar meu evento</Link><Link to="/ingressos">{publicText('tickets')}</Link><Link to="/login">Esqueci minha senha</Link></nav><Preferences/><button className="ghost-btn" onClick={()=>window.dispatchEvent(new Event('configure-cookies'))}>Configurar cookies</button></footer>}
export function CookieBanner(){const [choice,setChoice]=useState(()=>{try{return JSON.parse(localStorage.getItem('ingressos_cookies')||'null')}catch{return null}}),[open,setOpen]=useState(false),[analytics,setAnalytics]=useState(choice?.analytics||false);useEffect(()=>{const listener=()=>setOpen(true);window.addEventListener('configure-cookies',listener);return()=>window.removeEventListener('configure-cookies',listener)},[]);const save=value=>{const next={essential:true,analytics:value,at:new Date().toISOString(),version:16};localStorage.setItem('ingressos_cookies',JSON.stringify(next));setChoice(next);setOpen(false);window.dispatchEvent(new Event('cookie-consent'))};return (!choice||open)&&<aside className="cookies16" aria-label="Preferências de cookies"><h3>Sua privacidade faz parte da experiência.</h3><p>Armazenamento essencial mantém a sessão e suas escolhas. Medição de interesse é opcional.</p>{open&&<label className="check16"><input type="checkbox" checked={analytics} onChange={e=>setAnalytics(e.target.checked)}/>Permitir métricas de interesse anônimas</label>}<button className="primary-small" onClick={()=>save(open?analytics:true)}>{open?'Salvar escolhas':'Aceitar'}</button><button className="ghost-btn" onClick={()=>setOpen(true)}>Configurar</button><button className="ghost-btn" onClick={()=>save(false)}>Somente essenciais</button><Link to="/institucional/privacidade">Política de Privacidade</Link></aside>}
