import {useState} from 'react'
import {supabase} from '../lib/supabase'
import {useAuth,PRIMARY_ADMIN_EMAIL} from '../store/AuthStore'
import {useEventStore} from '../store/EventStore'
import './SalesCleanup.css'
export default function SalesCleanup({event,orders}){
 const {currentUser}=useAuth(),{refresh}=useEventStore()
 const [open,setOpen]=useState(false),[password,setPassword]=useState(''),[confirmation,setConfirmation]=useState(''),[selected,setSelected]=useState([]),[busy,setBusy]=useState(false),[message,setMessage]=useState('')
 if(!event||currentUser?.role!=='admin'||currentUser.email?.toLowerCase()!==PRIMARY_ADMIN_EMAIL)return null
 const available=Boolean(supabase)&&(import.meta.env.DEV||import.meta.env.VITE_SALES_MAINTENANCE_ENABLED==='true')
 const eligible=orders.filter(o=>o.eventId===event.id&&!o.paymentReview&&o.payoutStatus!=='paid'&&!(o.status==='approved'&&o.total>0))
 const chosen=eligible.filter(o=>selected.includes(o.id)),total=chosen.reduce((sum,o)=>sum+(o.total||0),0)
 async function clean(e){e.preventDefault();if(!available)return;setBusy(true);setMessage('');try{const {data:response,error}=await supabase.functions.invoke('sales-maintenance',{body:{eventId:event.id,orderIds:selected,password,confirmation}});if(error)throw error;if(response.error)throw Error(response.error);setMessage(`${response.count} pedido(s) de teste arquivado(s). Nenhum estorno foi realizado.`);setOpen(false);setSelected([]);refresh?.()}catch(err){let detail=err.message||'Não foi possível limpar.';try{const response=await err.context?.json();if(response?.error)detail=response.error}catch{/* Keep the safe fallback when the response cannot be read. */}setMessage(detail)}finally{setPassword('');setBusy(false)}}
 return <section className="sales-cleanup"><header><div><h2>Limpar vendas de teste</h2><p>Exclusivo Admin Geral. O evento, DJs, atrações e configurações são preservados.</p></div><button type="button" className="ghost-btn" onClick={()=>{setOpen(!open);setPassword('');setConfirmation('');setSelected([])}} disabled={busy||!available}>{open?'Fechar':'Revisar vendas de teste'}</button></header>{!available&&<p role="status">Limpeza de vendas temporariamente indisponível: instalação do serviço pendente.</p>}{open&&<form onSubmit={clean}><p>Selecione apenas pedidos de teste. Os registros ficam arquivados para auditoria; os ingressos selecionados serão cancelados e os testes sairão dos totais. Pagamentos aprovados, cobranças ativas e repasses são bloqueados no servidor.</p><div className="sales-cleanup-orders">{eligible.map(o=><label className="legal-choice" key={o.id}><input type="checkbox" disabled={busy} checked={selected.includes(o.id)} onChange={e=>setSelected(e.target.checked?[...selected,o.id]:selected.filter(id=>id!==o.id))}/><span>{o.buyer?.name||'Pedido'} • {o.id}<br/>{o.status} • {(o.total||0).toLocaleString('pt-BR',{style:'currency',currency:'BRL'})}</span></label>)}</div><p><strong>{chosen.length} pedidos selecionados • {total.toLocaleString('pt-BR',{style:'currency',currency:'BRL'})} nos registros selecionados</strong></p><label>Sua senha de Admin Geral<input type="password" autoComplete="current-password" required disabled={busy} value={password} onChange={e=>setPassword(e.target.value)}/></label><label>Digite LIMPAR VENDAS DE TESTE<input required disabled={busy} value={confirmation} onChange={e=>setConfirmation(e.target.value)}/></label><button className="ghost-btn" disabled={!supabase||busy||!selected.length||confirmation!=='LIMPAR VENDAS DE TESTE'||!password}>{busy?'Conferindo...':'Confirmar limpeza das vendas selecionadas'}</button>{!supabase&&<p>Disponível somente com o módulo de servidor instalado.</p>}</form>}{message&&<p role="status">{message}</p>}</section>
}
